site_name: Onboardly Documentation
site_url: ""
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.select

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: functionalities.md
  - Architecture: architecture.md
  - Experience: experience.md
  - Locust: locust.md